'use strict';
const pair=(en,ar)=>({en,ar});
const projects=[
{id:'noor',title:pair('NOOR Commerce','NOOR للتجارة'),category:'systems',type:pair('CLIENT PROJECT / COMMERCE','مشروع عميل / تجارة'),status:pair('Active development','قيد التطوير'),image:null,style:'noor-media',stack:'Flutter · Supabase · Firebase',desc:pair('A connected shopping ecosystem: customer app, vendor workspace, and administration tools.','منظومة تسوق مترابطة: تطبيق العملاء، ومساحة التجار، وأدوات الإدارة.'),problem:pair('Connect shopping, multi-vendor orders, and Noor-managed delivery in a single operational system.','ربط التسوق وطلبات التجار المتعددين والتوصيل الذي تديره نور في نظام تشغيلي واحد.'),role:pair('Mobile and dashboard engineering, backend integration, and product architecture.','هندسة تطبيق الهاتف ولوحة الإدارة، وربط الخلفية، وتصميم بنية المنتج.'),features:[pair('Customer shopping, cart, checkout, and order history.','تسوق العملاء والسلة وإتمام الطلب وسجل الطلبات.'),pair('Vendor product management and order preparation, with customer information kept out of vendor views.','إدارة منتجات التجار وتجهيز الطلبات، مع حماية معلومات العملاء من واجهات التجار.'),pair('Administration and delivery roles, notifications, coupons, and bilingual interfaces.','أدوار الإدارة والتوصيل، والإشعارات، والكوبونات، والواجهات ثنائية اللغة.')],note:pair('An active client engagement. Public launch and business outcome metrics are not claimed here.','مشروع عميل نشط. لا تُعرض هنا ادعاءات بإطلاق عام أو نتائج تجارية رقمية.'),url:'https://github.com/Joseph78888/noor-admin-dashboard'},
{id:'crop',title:pair('Crop Care','Crop Care'),category:'ai',type:pair('ACADEMIC PROJECT / EDGE AI','مشروع أكاديمي / ذكاء اصطناعي'),status:pair('Graduation project','مشروع تخرج'),image:'crop_care.webp',style:'crop-media',stack:'Flutter · Riverpod · TensorFlow Lite',desc:pair('Tomato leaf disease identification, with model inference running on the phone.','التعرف على أمراض أوراق الطماطم، مع تشغيل النموذج على الهاتف.'),problem:pair('Make a trained crop disease classifier usable through a mobile experience, without relying on a cloud request for every inference.','إتاحة نموذج تصنيف أمراض المحاصيل عبر تجربة هاتف، دون الاعتماد على طلب سحابي لكل عملية تحليل.'),role:pair('Flutter mobile application and model integration, working alongside teammates responsible for the AI model.','تطبيق Flutter وربط النموذج، بالتعاون مع أعضاء الفريق المسؤولين عن نموذج الذكاء الاصطناعي.'),features:[pair('MobileNetV2 model integration through TensorFlow Lite.','ربط نموذج MobileNetV2 عبر TensorFlow Lite.'),pair('Image capture, analysis results, history, and capture guidance.','التقاط الصور ونتائج التحليل والسجل وإرشادات التصوير.'),pair('Riverpod state management and a separate AI assistant experience.','إدارة الحالة عبر Riverpod وتجربة مساعد ذكاء اصطناعي منفصلة.')],note:pair('Academic research and a mobile implementation. The app presentation is reused from the original portfolio.','بحث أكاديمي وتنفيذ لتطبيق هاتف. الصورة المعروضة مأخوذة من ملف الأعمال الأصلي.'),url:'https://github.com/Joseph78888/Crop-Care-App'},
{id:'marketplace',title:pair('Local Services Marketplace','منصة الخدمات المحلية'),category:'systems',type:pair('CLIENT PROJECT / SERVICE MARKETPLACE','مشروع عميل / سوق خدمات'),status:pair('Discovery & proposal','استكشاف ومقترح'),image:null,style:'market-media',stack:'Proposed: Flutter · Supabase · Firebase',desc:pair('A clearer way to find a craftsperson, agree on a job, and follow it through.','طريقة أوضح للعثور على حرفي والاتفاق على العمل ومتابعته حتى الإكمال.'),problem:pair('Finding a worker is only the beginning. Customers need trust and visibility; providers need organized opportunities; operators need control.','العثور على عامل هو البداية فقط. يحتاج العميل للثقة والمتابعة، ومقدم الخدمة لفرص منظمة، والإدارة للتحكم.'),role:pair('Product discovery, MVP proposal, customer and provider journeys, business rules, and system architecture.','استكشاف المنتج ومقترح النسخة الأولية ورحلات العميل ومقدم الخدمة وقواعد العمل وبنية النظام.'),features:[pair('One proposed app with customer and provider modes, plus a separate responsive admin dashboard.','تطبيق مقترح بوضع العميل ومقدم الخدمة مع لوحة إدارة منفصلة ومتجاوبة.'),pair('Service categories, location-based discovery, request photos, scheduling, and quotes or site visits.','فئات الخدمات والبحث حسب الموقع وصور الطلب والمواعيد وعروض السعر أو المعاينة.'),pair('Provider approval, availability, job status history, completed-job reviews, and administrative oversight.','اعتماد مقدمي الخدمة والتوفر وسجل حالات العمل وتقييمات الأعمال المكتملة والإشراف الإداري.')],note:pair('Discovery and proposal stage. The workflows below describe the proposed MVP, not a launched platform.','في مرحلة الاستكشاف والمقترح. المسارات المعروضة تصف المنتج الأولي المقترح وليست منصة مطلقة.'),url:null}

];
projects[0].features.push(
 pair('Vendor onboarding includes store setup and an administration approval gate.','يشمل انضمام التاجر إعداد المتجر وبوابة اعتماد الإدارة.'),
 pair('Multi-vendor checkout creates a parent order and a separate sub-order for each vendor.','ينشئ الطلب متعدد التجار طلبًا رئيسيًا وطلبًا فرعيًا لكل تاجر.'),
 pair('Super admin, operations admin, and delivery admin have distinct responsibilities. Vendors confirm and prepare; Noor completes delivery.','لكل من الإدارة العليا والعمليات والتوصيل مسؤوليات منفصلة. يؤكد التاجر ويجهز، وتكمل نور التوصيل.'),
 pair('Coupons include the first-order 5,000 SDG offer, with dashboard management.','تشمل الكوبونات عرض 5,000 جنيه لأول طلب مع إدارته من اللوحة.'),
 pair('Order notifications open the relevant order, while administration broadcasts reach users.','تفتح إشعارات الطلب تفاصيله، وتصل الإشعارات العامة من الإدارة للمستخدمين.'),
 pair('Analytics cover revenue, sales growth, average order value, order count, and repeat customers, with explanations of each KPI.','تغطي التحليلات الإيرادات ونمو المبيعات ومتوسط قيمة الطلب وعدد الطلبات وتكرار العملاء مع شرح كل مؤشر.'),
 pair('Arabic and English span customer and vendor experiences, administration, and notifications.','تغطي العربية والإنجليزية تجارب العملاء والتجار والإدارة والإشعارات.'),
 pair('The development workflow includes GitHub Actions, automated checks, and Firebase tester distribution. Load testing is part of readiness work; capacity results are not claimed here.','يشمل التطوير GitHub Actions والفحوص الآلية وتوزيع النسخ للمختبرين عبر Firebase. اختبار الضغط جزء من الاستعداد ولا ندعي هنا نتائج سعة محددة.')
);
projects[1].features.push(pair('Reported per-class F1: Early Blight 0.91; Late Blight 0.93; Septoria 0.92; Bacterial Spot 0.94; TYLCV 0.97; Mosaic Virus 0.90.','قيم F1 المبلغ عنها: اللفحة المبكرة 0.91؛ اللفحة المتأخرة 0.93؛ سبتوريا 0.92؛ التبقع البكتيري 0.94؛ تجعد الأوراق الأصفر 0.97؛ فيروس الموزاييك 0.90.'),pair('Local image classification can operate without a network request. The Gemini assistant is a separate connected feature.','يعمل تصنيف الصور محليًا دون طلب شبكة. مساعد Gemini ميزة منفصلة تحتاج اتصالًا.'));
projects[2].features.push(pair('The proposed workflow records job status changes, supports quotes or inspection, and permits reviews only after completion.','يسجل المسار المقترح تغييرات حالة العمل ويدعم عروض السعر أو المعاينة ويتيح التقييم بعد الإكمال فقط.'),pair('Provider verification, availability rules, sensitive-contact visibility, cancellations, and disputes are defined in the proposal.','يحدد المقترح التحقق من مقدمي الخدمة وقواعد التوفر وظهور بيانات التواصل الحساسة والإلغاء والنزاعات.'));
const services=[
[pair('Mobile app development','تطوير تطبيقات الهاتف'),pair('Cross-platform Flutter products with a considered user experience and a maintainable foundation.','منتجات Flutter متعددة المنصات بتجربة استخدام مدروسة وأساس قابل للصيانة.'),['Flutter','iOS & Android','Riverpod / Bloc']],
[pair('Business platforms & systems','منصات وأنظمة الأعمال'),pair('Customer apps, administration tools, and backend workflows designed to operate together.','تطبيقات العملاء وأدوات الإدارة والعمليات الخلفية، مصممة لتعمل معًا.'),['Commerce','Operations','Supabase / Firebase']],
[pair('Product design & user journeys','تصميم المنتجات ورحلات المستخدم'),pair('Clarify the flow, define the interface, and connect design decisions to the job your customer needs to do.','توضيح المسار وتحديد الواجهة وربط قرارات التصميم بما يحتاجه عميلك.'),['User flows','Interface design','Product scope']],
[pair('MVP planning & delivery','تخطيط وتسليم المنتج الأولي'),pair('Find the smallest useful product, agree on milestones, and build a first version you can learn from.','تحديد أصغر منتج مفيد، والاتفاق على المراحل، وبناء نسخة أولى للتعلم منها.'),['Discovery','Feasibility','Iterative releases']],
[pair('On-device AI integration','دمج الذكاء الاصطناعي على الجهاز'),pair('Bring trained models into practical mobile experiences with attention to inference and offline use.','دمج النماذج المدربة في تجارب هاتف عملية مع الاهتمام بالتشغيل والاستخدام دون اتصال.'),['TensorFlow Lite','Model integration','Edge AI']],
[pair('A strong foundation for what comes next.','أساس قوي لما يأتي بعده.'),pair('Clean architecture, clear responsibilities, and a release workflow that supports the next phase of your product.','بنية نظيفة، ومسؤوليات واضحة، ومسار إصدار يدعم المرحلة القادمة من منتجك.'),['Architecture','CI/CD','Documentation']]
];
const processes=[
[pair('Understand','نفهم'),pair('Define the business problem, users, constraints, and a useful first scope.','نحدد مشكلة العمل والمستخدمين والقيود ونطاقًا أوليًا مفيدًا.')],
[pair('Design the system','نصمم النظام'),pair('Map user journeys, interface decisions, data, and responsibilities before implementation.','نرسم رحلات المستخدم وقرارات الواجهة والبيانات والمسؤوليات قبل التنفيذ.')],
[pair('Build & validate','نبني ونختبر'),pair('Develop in reviewable steps. Test behavior, devices, and the workflows that matter.','نطوّر بخطوات قابلة للمراجعة، ونختبر السلوك والأجهزة ومسارات العمل المهمة.')],
[pair('Release & evolve','نطلق ونطوّر'),pair('Prepare deployment, document the system, and plan the next iteration with you.','نجهز النشر ونوثق النظام ونخطط معك للتطوير القادم.')]
];
const labs=[
[pair('Fuel quota system','نظام حصص الوقود'),pair('Proposal & discovery','مقترح واستكشاف'),pair('Vehicle-based fuel allowances, station verification, and operations oversight for transport businesses.','حصص وقود مرتبطة بالمركبات، والتحقق في المحطات، والإشراف التشغيلي لأعمال النقل.'),pair('TRANSPORT / OPERATIONS','النقل / العمليات')],
[pair('Medical apparel store','متجر الملابس الطبية'),pair('Requirements exploration','استكشاف المتطلبات'),pair('Exploring online retail for lab coats and scrubs across Egypt and Sudan.','استكشاف البيع الإلكتروني للابكوت والملابس الطبية في مصر والسودان.'),pair('COMMERCE / REGIONAL MARKETS','تجارة / أسواق إقليمية')]
];
const faqs=[
[pair('Can we start with just an idea?','هل يمكن البدء بفكرة فقط؟'),pair('Yes. Start with the problem, who experiences it, and what you want to achieve. Discovery helps define a sensible first version before committing to a large scope.','نعم. نبدأ بالمشكلة ومن يواجهها وما تريد تحقيقه. يساعد الاستكشاف في تحديد نسخة أولى مناسبة قبل الالتزام بنطاق كبير.')],
[pair('Can you improve an existing product?','هل يمكن تحسين منتج قائم؟'),pair('Yes. We start by reviewing the architecture, user journeys, and current constraints. Then we agree on a focused improvement plan.','نعم. نبدأ بمراجعة البنية ورحلات المستخدم والقيود الحالية، ثم نتفق على خطة تحسين محددة.')],
[pair('How are timelines and budgets decided?','كيف تُحدد المدة والميزانية؟'),pair('They depend on scope, integrations, design readiness, and delivery requirements. We agree on milestones and responsibilities after reviewing the project.','تعتمد على النطاق والتكاملات وجاهزية التصميم ومتطلبات التسليم. نتفق على المراحل والمسؤوليات بعد مراجعة المشروع.')],
[pair('Who will build our product?','من سيبني منتجنا؟'),pair('We agree on project ownership, responsibilities, and communication before work begins. Yousif leads the studio as founder; specialist collaboration is scoped to the needs of each engagement.','نحدد ملكية المشروع والمسؤوليات والتواصل قبل بدء العمل. يقود يوسف الاستوديو بصفته المؤسس، ويُحدد التعاون مع المختصين وفق احتياجات كل مشروع.')]
];
let lang='en',filter='all',activeProject=null;
const $=id=>document.getElementById(id),t=v=>v[lang],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readPref=k=>{try{return localStorage.getItem(k)}catch{return null}},writePref=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
function renderProjects(){
 const options=[['all',pair('All projects','كل المشاريع')],['systems',pair('Business platforms','منصات الأعمال')],['ai',pair('Applied AI','ذكاء اصطناعي تطبيقي')]];
 $('filters').innerHTML=options.map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${esc(t(label))}</button>`).join('');
 $('projects').innerHTML=projects.filter(p=>filter==='all'||p.category===filter).map(p=>caseStudy(p)).join('');
}
const L=(en,ar)=>lang==='en'?en:ar;
const cell=(en,ar,bodyEn,bodyAr)=>`<div class="case-fact"><h4>${L(en,ar)}</h4><p>${L(bodyEn,bodyAr)}</p></div>`;
let noorView='customer';
function noorVisual(){
 const views={customer:[L('Customer experience','تجربة العميل'),L('Discover. Choose. Order.','اكتشف. اختر. اطلب.'),[L('Browse stores & categories','تصفح المتاجر والفئات'),L('Cart, coupon & saved address','السلة والكوبون والعنوان المحفوظ'),L('Cash on delivery checkout','إتمام الطلب بالدفع عند الاستلام'),L('Order history & notifications','سجل الطلبات والإشعارات')]],vendor:[L('Vendor workspace','مساحة التاجر'),L('Your store. In control.','متجرك. تحت إدارتك.'),[L('Store approval & setup','إعداد المتجر واعتماده'),L('Products, images & inventory','المنتجات والصور والمخزون'),L('Confirm & prepare orders','تأكيد الطلبات وتجهيزها'),L('Delivered sales & reports','المبيعات المسلّمة والتقارير')]],operations:[L('Noor Dashboard','لوحة إدارة نور'),L('One view of the operation.','رؤية واحدة للعملية.'),[L('Parent orders & vendor sub-orders','الطلب الرئيسي وطلبات التجار الفرعية'),L('Admin & delivery permissions','صلاحيات الإدارة والتوصيل'),L('Coupons, categories & broadcasts','الكوبونات والفئات والإشعارات العامة'),L('Revenue, AOV & repeat customers','الإيرادات ومتوسط الطلب وتكرار الشراء')]]};
 const v=views[noorView];
 return `<div class="ecosystem"><div class="visual-top"><b>NOOR<span>${L('Commerce ecosystem','منظومة التجارة')}</span></b><span class="visual-caption">${L('Interface study','عرض توضيحي للواجهة')}</span></div><div class="view-switch" role="group" aria-label="${L('Explore Noor experiences','استكشف تجارب نور')}">${Object.keys(views).map(k=>`<button data-noor-view="${k}" aria-pressed="${noorView===k}">${views[k][0]}</button>`).join('')}</div><div class="workspace-preview" key="${noorView}"><div class="workspace-side"><span>NOOR / ${L('WORKSPACE','مساحة العمل')}</span><b>${v[0]}</b><div class="workspace-lines"><i></i><i></i><i></i></div></div><div class="workspace-main"><small>${L('DESIGNED AROUND THE WHOLE JOURNEY','مصمم حول الرحلة الكاملة')}</small><h4>${v[1]}</h4><div class="workspace-items">${v[2].map((x,i)=>`<div><span>0${i+1}</span><strong>${x}</strong></div>`).join('')}</div></div></div><div class="journey" aria-label="${L('Order lifecycle','دورة الطلب')}">${[L('Order','طلب'),L('Confirm','تأكيد'),L('Prepare','تجهيز'),L('Deliver','توصيل')].map((x,i)=>`<span style="--step:${i}"><i></i>${x}</span>`).join('')}</div></div>`;
}
function caseStudy(p){
 const noor=p.id==='noor',crop=p.id==='crop';
 const headline=noor?L('One marketplace. Every part connected.','سوق واحد. وكل جزء مترابط.'):crop?L('Useful AI, right where it is needed.','ذكاء اصطناعي مفيد حيث تحتاجه.'):L('Turn local expertise into a trusted service.','حوّل الخبرة المحلية إلى خدمة موثوقة.');
 const visual=noor?`<div id="noor-visual">${noorVisual()}</div>`:crop?`<div class="crop-presentation"><img src="assets/images/crop_care.webp" alt="${L('Original Crop Care app presentation, showing capture and analysis screens','عرض تطبيق Crop Care الأصلي مع شاشات الالتقاط والتحليل')}" width="1200" height="541" loading="lazy"><p>${L('Original project presentation · screen values are illustrative','عرض المشروع الأصلي · قيم الشاشات توضيحية')}</p><div class="inference-path">${[L('Capture a leaf','التقط الورقة'),L('On-device model','نموذج على الجهاز'),L('Review & save','راجع واحفظ')].map((x,i)=>`<span><b>0${i+1}</b>${x}</span>`).join('')}</div></div>`:`<div class="marketplace-preview"><div class="visual-top"><b>${L('LOCAL / SERVICES','خدمات / محلية')}<span>${L('Proposed product journey','رحلة المنتج المقترحة')}</span></b><span class="visual-caption">${L('Concept','تصور')}</span></div><h4>${L('A job request, with a clear next step.','طلب خدمة بخطوة قادمة واضحة.')}</h4><div class="service-options"><span>${L('Electrical','كهرباء')}</span><span>${L('Plumbing','سباكة')}</span><span>${L('Repairs','صيانة')}</span></div><ol>${[L('Describe the job, location & preferred time','صف العمل والموقع والوقت المناسب'),L('Review a provider & agree on the quote','راجع مقدم الخدمة واتفق على السعر'),L('Follow the job from acceptance to completion','تابع العمل من القبول حتى الإكمال'),L('Review the completed service','قيّم الخدمة المكتملة')].map(x=>`<li>${x}</li>`).join('')}</ol><div class="trust-row"><span>${L('Admin approval','اعتماد الإدارة')}</span><span>${L('Availability','التوفر')}</span><span>${L('Job history','سجل العمل')}</span></div></div>`;
 let facts=noor?cell('For customers','للعملاء','Browse products and stores, save addresses, use coupons, and follow orders in Arabic or English.','تصفح المنتجات والمتاجر واحفظ العناوين واستخدم الكوبونات وتابع الطلبات بالعربية أو الإنجليزية.')+cell('For vendors','للتجار','Manage products and inventory, prepare incoming orders, and review delivered sales without exposing customer personal data.','أدر المنتجات والمخزون وجهّز الطلبات وراجع المبيعات المسلّمة دون كشف بيانات العملاء الشخصية.')+cell('For operations','للعمليات','A separate Windows and Android dashboard connects order control, delivery roles, categories, broadcasts, coupons, and analytics.','لوحة منفصلة لويندوز وأندرويد تربط إدارة الطلبات وأدوار التوصيل والفئات والإشعارات والكوبونات والتحليلات.'):crop?cell('A practical mobile journey','رحلة هاتف عملية','Capture or select a leaf image, review the result, revisit history, and get guidance on taking a useful photo.','التقط أو اختر صورة الورقة وراجع النتيجة والسجل واحصل على إرشادات لالتقاط صورة مفيدة.')+cell('AI on the device','ذكاء على الجهاز','MobileNetV2 processes 224 × 224 images through TensorFlow Lite. Classification runs locally; the separate AI assistant needs connectivity.','يعالج MobileNetV2 صورًا بحجم 224 × 224 عبر TensorFlow Lite. التصنيف محلي؛ والمساعد المنفصل يحتاج اتصالًا.')+cell('Confidence with context','ثقة مع سياق','A 0.79 confidence threshold supports an unknown result. This is an academic classifier, with model research contributed by the AI teammates.','عتبة ثقة 0.79 تدعم نتيجة غير معروفة. هذا مصنف أكاديمي؛ وقد شارك أعضاء فريق الذكاء الاصطناعي في بحث النموذج.'):cell('Customer clarity','وضوح للعميل','Search by service and location, add request photos, arrange a time, and confirm a price or inspection.','ابحث حسب الخدمة والموقع وأضف صور الطلب وحدد موعدًا واتفق على سعر أو معاينة.')+cell('Provider opportunity','فرص لمقدم الخدمة','The proposed provider mode brings together approval, availability, incoming requests, work history, and reviews.','يجمع وضع مقدم الخدمة المقترح الاعتماد والتوفر والطلبات الواردة وسجل العمل والتقييمات.')+cell('Operator oversight','إشراف الإدارة','A responsive dashboard is scoped for provider verification, categories, requests, notifications, and basic reports.','لوحة متجاوبة مخطط لها للتحقق من مقدمي الخدمة والفئات والطلبات والإشعارات والتقارير الأساسية.');
 const reason=noor?L('Building a commerce business takes more than a storefront. NOOR shows how we connect customer experience to the systems that keep orders moving.','بناء تجارة رقمية يحتاج أكثر من واجهة متجر. نور توضح كيف نربط تجربة العميل بالأنظمة التي تحرك الطلبات.'):crop?L('A trained model only becomes useful when people can use it. Crop Care demonstrates the bridge between AI research and a usable mobile product.','يصبح النموذج المدرب مفيدًا عندما يستطيع الناس استخدامه. Crop Care تربط البحث في الذكاء الاصطناعي بمنتج هاتف عملي.'):L('A marketplace needs clear rules before it needs more features. This work defines trust, responsibilities, and the service lifecycle before implementation.','يحتاج السوق لقواعد واضحة قبل المزيد من الميزات. يحدد هذا العمل الثقة والمسؤوليات ودورة الخدمة قبل التنفيذ.');
 const extra=noor?`<div class="delivery-note"><b>${L('Built for the local operating model','مبني لنموذج التشغيل المحلي')}</b><p>${L('Cash on delivery for the MVP. Noor manages delivery in-house. The first ordering rollout is scoped to Sinnar, with other cities planned later. Role-based access separates vendor preparation from delivery completion.','الدفع عند الاستلام للنسخة الأولى. نور تدير التوصيل داخليًا. يبدأ نطاق الطلبات بسنار مع التخطيط لمدن أخرى لاحقًا. تفصل الصلاحيات تجهيز التاجر عن إكمال التوصيل.')}</p></div>`:crop?`<div class="delivery-note"><b>${L('Reported model evaluation','تقييم النموذج المبلغ عنه')}</b><p>${L('F1 scores across six reported disease classes: 0.90–0.97. These are research evaluation results, not a promise of field accuracy.','قيم F1 لست فئات أمراض مبلغ عنها: 0.90–0.97. هذه نتائج تقييم بحثي وليست ضمانًا للدقة في الحقل.')}</p></div>`:'';
 return `<article id="case-${p.id}" class="project-card case-study ${noor?'case-featured':''}"><div class="case-heading"><div class="case-label"><span>${noor?'01':crop?'02':'03'} / ${esc(t(p.title))}</span><span>${esc(t(p.status))}</span></div><h3>${headline}</h3><p>${esc(t(p.desc))}</p></div><div class="case-stage">${visual}<div class="case-summary"><span class="eyebrow">${L('The business challenge','تحدي الأعمال')}</span><h4>${noor?L('Shopping is the beginning. Operations make it work.','التسوق هو البداية. التشغيل يجعله ممكنًا.'):crop?L('From an image to an informed next step.','من صورة إلى خطوة مدروسة.'):L('Trust at every step of the service.','الثقة في كل خطوة من الخدمة.')}</h4><p>${esc(t(p.problem))}</p><div class="case-scope"><b>${L('Scope','النطاق')}</b><span>${esc(p.stack)}</span></div><button class="button secondary" data-project="${p.id}">${L('Explore the full case study','استكشف دراسة المشروع الكاملة')}</button></div></div><div class="case-facts">${facts}</div>${extra}<div class="case-bottom"><p>${reason}</p><a href="#contact" class="button primary" data-enquiry="${p.id}">${noor?L('Build a connected platform','ابنِ منصة مترابطة'):crop?L('Bring AI into your product','أضف الذكاء إلى منتجك'):L('Plan your marketplace','خطط لسوقك')}</a></div></article>`;
}
function renderAll(){
 document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
 document.querySelectorAll('[data-en][data-ar]').forEach(el=>el.textContent=el.dataset[lang]);
 $('language').textContent=lang==='en'?'عربي':'EN';$('language').lang=lang==='en'?'ar':'en';$('language').ariaLabel=lang==='en'?'Switch to Arabic':'التبديل إلى الإنجليزية';
 document.title=lang==='en'?'Yousif Digital | Product Design & Software Engineering':'يوسف ديجيتال | تصميم المنتجات وهندسة البرمجيات';
 $('filters').ariaLabel=lang==='en'?'Filter projects':'تصفية المشاريع';$('close-dialog').ariaLabel=lang==='en'?'Close project details':'إغلاق تفاصيل المشروع';
 renderProjects();
 $('service-list').innerHTML=services.map(([title,desc,tags],i)=>`<article class="service-card"><span class="service-number">0${i+1}</span><h3>${esc(t(title))}</h3><p>${esc(t(desc))}</p><div class="tags">${tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></article>`).join('');

 $('process-list').innerHTML=processes.map(([title,desc],i)=>`<article class="process-card"><span>0${i+1}</span><h3>${esc(t(title))}</h3><p>${esc(t(desc))}</p></article>`).join('');
 $('lab-list').innerHTML=labs.map(([title,status,desc,type])=>`<article class="lab-card"><span class="lab-status">${esc(t(status))}</span><h3>${esc(t(title))}</h3><p>${esc(t(desc))}</p><div class="lab-type">${esc(t(type))}</div></article>`).join('');
 $('faq-list').innerHTML=faqs.map(([q,a])=>`<details><summary>${esc(t(q))}</summary><p>${esc(t(a))}</p></details>`).join('');
 if(activeProject)renderDialog(activeProject);updateThemeLabel();refreshMotion();
}
function renderDialog(p){
 const block=(title,body)=>`<div class="detail-block"><h3>${title}</h3>${body}</div>`;
 $('dialog-content').innerHTML=`<p class="dialog-kicker">${esc(t(p.type))} · ${esc(t(p.status))}</p><h2 id="dialog-title">${esc(t(p.title))}</h2><p>${esc(t(p.desc))}</p>${block(lang==='en'?'The challenge':'التحدي',`<p>${esc(t(p.problem))}</p>`)}${block(lang==='en'?'Project contribution':'المساهمة في المشروع',`<p>${esc(t(p.role))}</p>`)}${block(lang==='en'?'What the work covers':'ما يشمله العمل',`<ul>${p.features.map(f=>`<li>${esc(t(f))}</li>`).join('')}</ul>`)}${block(lang==='en'?'Technology & stage':'التقنيات والمرحلة',`<p dir="ltr">${esc(p.stack)}</p><p>${esc(t(p.note))}</p>`)}${p.url?`<a class="button secondary" href="${p.url}" target="_blank" rel="noopener noreferrer">${L('View repository on GitHub','عرض المستودع على GitHub')}</a>`:''}<a class="button primary dialog-contact" href="#contact">${L('Discuss a similar project','ناقش مشروعًا مشابهًا')}</a>`;
}
$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;renderProjects();$('filters').querySelector(`[data-filter="${filter}"]`).focus();refreshMotion()});
$('projects').addEventListener('click',e=>{const view=e.target.closest('[data-noor-view]');if(view){noorView=view.dataset.noorView;$('noor-visual').innerHTML=noorVisual();$('noor-visual').querySelector(`[data-noor-view="${noorView}"]`).focus();return;}const b=e.target.closest('[data-project]');if(!b)return;activeProject=projects.find(p=>p.id===b.dataset.project);renderDialog(activeProject);$('project-dialog').showModal();document.body.style.overflow='hidden'});
$('close-dialog').addEventListener('click',()=>$('project-dialog').close());$('project-dialog').addEventListener('click',e=>{if(e.target===$('project-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});$('project-dialog').addEventListener('close',()=>{activeProject=null;document.body.style.overflow=''});
$('language').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';writePref('portfolio-language',lang);$('copy-status').textContent='';renderAll()});
function updateThemeLabel(){const dark=document.documentElement.dataset.theme==='dark';$('theme').ariaLabel=lang==='en'?(dark?'Switch to light theme':'Switch to dark theme'):(dark?'تفعيل المظهر الفاتح':'تفعيل المظهر الداكن')}
$('theme').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';writePref('portfolio-theme',document.documentElement.dataset.theme);updateThemeLabel()});
$('menu').addEventListener('click',()=>{const expanded=$('menu').getAttribute('aria-expanded')==='true';$('menu').setAttribute('aria-expanded',String(!expanded));$('nav-links').classList.toggle('open',!expanded)});
$('nav-links').addEventListener('click',e=>{if(e.target.closest('a')){$('menu').setAttribute('aria-expanded','false');$('nav-links').classList.remove('open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('menu').setAttribute('aria-expanded','false');$('nav-links').classList.remove('open')}});
$('copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('yousifkhalid544@gmail.com');$('copy-status').textContent=lang==='en'?'Email copied.':'تم نسخ البريد.'}catch{$('copy-status').textContent=lang==='en'?'Select the email above to copy it.':'حدد البريد أعلاه لنسخه.'}});
$('contact-form').addEventListener('submit',e=>{e.preventDefault();const name=$('name').value.trim(),email=$('email').value.trim(),message=$('message').value.trim();if(!name||!message)return;const subject=lang==='en'?`Project enquiry from ${name}`:`استفسار مشروع من ${name}`;const body=`${name}\n${email}\n\n${message}`;window.location.href=`mailto:yousifkhalid544@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
$('dialog-content').addEventListener('click',e=>{if(e.target.closest('.dialog-contact'))$('project-dialog').close()});
let revealObserver=null;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
let motionPaused=readPref('studio-motion')==='off';
function refreshMotion(){
 const off=motionPaused||reducedMotion.matches;
 document.documentElement.dataset.motion=off?'off':'on';
 $('motion-toggle').textContent=lang==='en'?(off?'Enable motion':'Pause motion'):(off?'تفعيل الحركة':'إيقاف الحركة');
 $('motion-toggle').setAttribute('aria-pressed',String(off));
 if(revealObserver)revealObserver.disconnect();
 if(off||!('IntersectionObserver' in window)){document.documentElement.classList.remove('motion-ready');return;}
 document.documentElement.classList.add('motion-ready');
 revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}})},{threshold:.08,rootMargin:'0px 0px -25px 0px'});
 document.querySelectorAll('.heading,.impact-card,.service-card,.project-card,.process-card,.model-card,.company-grid,.lab-card,.faq>div,.contact-grid').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--reveal-delay',`${(i%3)*50}ms`);revealObserver.observe(el)});
}
$('motion-toggle').addEventListener('click',()=>{motionPaused=!motionPaused;writePref('studio-motion',motionPaused?'off':'on');refreshMotion()});
reducedMotion.addEventListener('change',refreshMotion);
lang=readPref('portfolio-language')==='ar'?'ar':'en';document.documentElement.dataset.theme=readPref('portfolio-theme')==='dark'?'dark':'light';renderAll();
