'use strict';
const pair=(en,ar)=>({en,ar});
const projects=[
{id:'noor',title:pair('NOOR Commerce','NOOR للتجارة'),category:'systems',type:pair('CLIENT PROJECT / COMMERCE','مشروع عميل / تجارة'),status:pair('Active development','قيد التطوير'),image:null,style:'noor-media',stack:'Flutter · Supabase · Firebase',desc:pair('A connected shopping ecosystem: customer app, vendor workspace, and administration tools.','منظومة تسوق مترابطة: تطبيق العملاء، ومساحة التجار، وأدوات الإدارة.'),problem:pair('Connect shopping, multi-vendor orders, and Noor-managed delivery in a single operational system.','ربط التسوق وطلبات التجار المتعددين والتوصيل الذي تديره نور في نظام تشغيلي واحد.'),role:pair('Mobile and dashboard engineering, backend integration, and product architecture.','هندسة تطبيق الهاتف ولوحة الإدارة، وربط الخلفية، وتصميم بنية المنتج.'),features:[pair('Customer shopping, cart, checkout, and order history.','تسوق العملاء والسلة وإتمام الطلب وسجل الطلبات.'),pair('Vendor product management and order preparation, with customer information kept out of vendor views.','إدارة منتجات التجار وتجهيز الطلبات، مع حماية معلومات العملاء من واجهات التجار.'),pair('Administration and delivery roles, notifications, coupons, and bilingual interfaces.','أدوار الإدارة والتوصيل، والإشعارات، والكوبونات، والواجهات ثنائية اللغة.')],note:pair('An active client engagement. Public launch and business outcome metrics are not claimed here.','مشروع عميل نشط. لا تُعرض هنا ادعاءات بإطلاق عام أو نتائج تجارية رقمية.'),url:'https://github.com/Joseph78888/noor-admin-dashboard'},
{id:'crop',title:pair('Crop Care','Crop Care'),category:'ai',type:pair('ACADEMIC PROJECT / EDGE AI','مشروع أكاديمي / ذكاء اصطناعي'),status:pair('Graduation project','مشروع تخرج'),image:'crop_care.webp',style:'crop-media',stack:'Flutter · Riverpod · TensorFlow Lite',desc:pair('Tomato leaf disease identification, with model inference running on the phone.','التعرف على أمراض أوراق الطماطم، مع تشغيل النموذج على الهاتف.'),problem:pair('Make a trained crop disease classifier usable through a mobile experience, without relying on a cloud request for every inference.','إتاحة نموذج تصنيف أمراض المحاصيل عبر تجربة هاتف، دون الاعتماد على طلب سحابي لكل عملية تحليل.'),role:pair('Flutter mobile application and model integration, working alongside teammates responsible for the AI model.','تطبيق Flutter وربط النموذج، بالتعاون مع أعضاء الفريق المسؤولين عن نموذج الذكاء الاصطناعي.'),features:[pair('MobileNetV2 model integration through TensorFlow Lite.','ربط نموذج MobileNetV2 عبر TensorFlow Lite.'),pair('Image capture, analysis results, history, and capture guidance.','التقاط الصور ونتائج التحليل والسجل وإرشادات التصوير.'),pair('Riverpod state management and a separate AI assistant experience.','إدارة الحالة عبر Riverpod وتجربة مساعد ذكاء اصطناعي منفصلة.')],note:pair('Academic research and a mobile implementation. Presentation mockups illustrate the app’s workflows.','بحث أكاديمي وتنفيذ لتطبيق هاتف. توضح نماذج العرض مسارات التطبيق.'),url:'https://github.com/Joseph78888/Crop-Care-App'},
{id:'marketplace',title:pair('Local Services Marketplace','منصة الخدمات المحلية'),category:'systems',type:pair('CLIENT PROJECT / SERVICE MARKETPLACE','مشروع عميل / سوق خدمات'),status:pair('Discovery & proposal','استكشاف ومقترح'),image:null,style:'market-media',stack:'Proposed: Flutter · Supabase · Firebase',desc:pair('A clearer way to find a craftsperson, agree on a job, and follow it through.','طريقة أوضح للعثور على حرفي والاتفاق على العمل ومتابعته حتى الإكمال.'),problem:pair('Finding a worker is only the beginning. Customers need trust and visibility; providers need organized opportunities; operators need control.','العثور على عامل هو البداية فقط. يحتاج العميل للثقة والمتابعة، ومقدم الخدمة لفرص منظمة، والإدارة للتحكم.'),role:pair('Product discovery, MVP proposal, customer and provider journeys, business rules, and system architecture.','استكشاف المنتج ومقترح النسخة الأولية ورحلات العميل ومقدم الخدمة وقواعد العمل وبنية النظام.'),features:[pair('One proposed app with customer and provider modes, plus a separate responsive admin dashboard.','تطبيق مقترح بوضع العميل ومقدم الخدمة مع لوحة إدارة منفصلة ومتجاوبة.'),pair('Service categories, location-based discovery, request photos, scheduling, and quotes or site visits.','فئات الخدمات والبحث حسب الموقع وصور الطلب والمواعيد وعروض السعر أو المعاينة.'),pair('Provider approval, availability, job status history, completed-job reviews, and administrative oversight.','اعتماد مقدمي الخدمة والتوفر وسجل حالات العمل وتقييمات الأعمال المكتملة والإشراف الإداري.')],note:pair('Discovery and proposal stage. The workflows below describe the proposed MVP, not a launched platform.','في مرحلة الاستكشاف والمقترح. المسارات المعروضة تصف المنتج الأولي المقترح وليست منصة مطلقة.'),url:null}

];
projects[0].features.push(
 pair('Vendor onboarding includes store setup and an administration approval gate.','يشمل انضمام التاجر إعداد المتجر وبوابة اعتماد الإدارة.'),
 pair('Multi-vendor checkout creates a parent order and a separate sub-order for each vendor.','ينشئ الطلب متعدد التجار طلبًا رئيسيًا وطلبًا فرعيًا لكل تاجر.'),
 pair('Super admin, operations admin, and delivery admin have distinct responsibilities. Vendors confirm and prepare; Noor completes delivery.','لكل من الإدارة العليا والعمليات والتوصيل مسؤوليات منفصلة. يؤكد التاجر ويجهز، وتكمل نور التوصيل.'),
 pair('Coupons include the first-order 5,000 SDG offer, with dashboard management.','تشمل الكوبونات عرض 5,000 جنيه لأول طلب مع إدارته من اللوحة.'),
 pair('Order notifications open the relevant order, while administration broadcasts reach users.','تفتح إشعارات الطلب تفاصيله، وتصل الإشعارات العامة من الإدارة للمستخدمين.'),
 pair('Analytics cover revenue, sales growth, average order value, order count, and repeat customers, with explanations of each KPI.','تغطي التحليلات الإيرادات ونمو المبيعات ومتوسط قيمة الطلب وعدد الطلبات وتكرار العملاء مع شرح كل مؤشر.'),
 pair('Arabic and English span customer and vendor experiences, administration, and notifications.','تغطي العربية والإنجليزية تجارب العملاء والتجار والإدارة والإشعارات.'),
 pair('The development workflow includes GitHub Actions, automated checks, and Firebase tester distribution. Load testing is part of readiness work; capacity results are not claimed here.','يشمل التطوير GitHub Actions والفحوص الآلية وتوزيع النسخ للمختبرين عبر Firebase. اختبار الضغط جزء من الاستعداد ولا ندعي هنا نتائج سعة محددة.')
);
projects[1].features.push(pair('Reported per-class F1: Early Blight 0.91; Late Blight 0.93; Septoria 0.92; Bacterial Spot 0.94; TYLCV 0.97; Mosaic Virus 0.90.','قيم F1 المبلغ عنها: اللفحة المبكرة 0.91؛ اللفحة المتأخرة 0.93؛ سبتوريا 0.92؛ التبقع البكتيري 0.94؛ تجعد الأوراق الأصفر 0.97؛ فيروس الموزاييك 0.90.'),pair('Local image classification can operate without a network request. The Gemini assistant is a separate connected feature.','يعمل تصنيف الصور محليًا دون طلب شبكة. مساعد Gemini ميزة منفصلة تحتاج اتصالًا.'));
projects[2].features.push(pair('The proposed workflow records job status changes, supports quotes or inspection, and permits reviews only after completion.','يسجل المسار المقترح تغييرات حالة العمل ويدعم عروض السعر أو المعاينة ويتيح التقييم بعد الإكمال فقط.'),pair('Provider verification, availability rules, sensitive-contact visibility, cancellations, and disputes are defined in the proposal.','يحدد المقترح التحقق من مقدمي الخدمة وقواعد التوفر وظهور بيانات التواصل الحساسة والإلغاء والنزاعات.'));
const services=[
[pair('Mobile app development','تطوير تطبيقات الهاتف'),pair('Cross-platform Flutter products with a considered user experience and a maintainable foundation.','منتجات Flutter متعددة المنصات بتجربة استخدام مدروسة وأساس قابل للصيانة.'),['Flutter','iOS & Android','Riverpod / Bloc']],
[pair('Business platforms & systems','منصات وأنظمة الأعمال'),pair('Customer apps, administration tools, and backend workflows designed to operate together.','تطبيقات العملاء وأدوات الإدارة والعمليات الخلفية، مصممة لتعمل معًا.'),['Commerce','Operations','Supabase / Firebase']],
[pair('Product design & user journeys','تصميم المنتجات ورحلات المستخدم'),pair('Clarify the flow, define the interface, and connect design decisions to the job your customer needs to do.','توضيح المسار وتحديد الواجهة وربط قرارات التصميم بما يحتاجه عميلك.'),['User flows','Interface design','Product scope']],
[pair('MVP planning & delivery','تخطيط وتسليم المنتج الأولي'),pair('Find the smallest useful product, agree on milestones, and build a first version you can learn from.','تحديد أصغر منتج مفيد، والاتفاق على المراحل، وبناء نسخة أولى للتعلم منها.'),['Discovery','Feasibility','Iterative releases']],
[pair('On-device AI integration','دمج الذكاء الاصطناعي على الجهاز'),pair('Bring trained models into practical mobile experiences with attention to inference and offline use.','دمج النماذج المدربة في تجارب هاتف عملية مع الاهتمام بالتشغيل والاستخدام دون اتصال.'),['TensorFlow Lite','Model integration','Edge AI']],
[pair('A strong foundation for what comes next.','أساس قوي لما يأتي بعده.'),pair('Clean architecture, clear responsibilities, and a release workflow that supports the next phase of your product.','بنية نظيفة، ومسؤوليات واضحة، ومسار إصدار يدعم المرحلة القادمة من منتجك.'),['Architecture','CI/CD','Documentation']]
];
const processes=[
[pair('Understand','نفهم'),pair('Define the business problem, users, constraints, and a useful first scope.','نحدد مشكلة العمل والمستخدمين والقيود ونطاقًا أوليًا مفيدًا.')],
[pair('Design the system','نصمم النظام'),pair('Map user journeys, interface decisions, data, and responsibilities before implementation.','نرسم رحلات المستخدم وقرارات الواجهة والبيانات والمسؤوليات قبل التنفيذ.')],
[pair('Build & validate','نبني ونختبر'),pair('Develop in reviewable steps. Test behavior, devices, and the workflows that matter.','نطوّر بخطوات قابلة للمراجعة، ونختبر السلوك والأجهزة ومسارات العمل المهمة.')],
[pair('Release & evolve','نطلق ونطوّر'),pair('Prepare deployment, document the system, and plan the next iteration with you.','نجهز النشر ونوثق النظام ونخطط معك للتطوير القادم.')]
];
const labs=[
[pair('Fuel quota system','نظام حصص الوقود'),pair('Proposal & discovery','مقترح واستكشاف'),pair('Vehicle-based fuel allowances, station verification, and operations oversight for transport businesses.','حصص وقود مرتبطة بالمركبات، والتحقق في المحطات، والإشراف التشغيلي لأعمال النقل.'),pair('TRANSPORT / OPERATIONS','النقل / العمليات')],
[pair('Medical apparel store','متجر الملابس الطبية'),pair('Requirements exploration','استكشاف المتطلبات'),pair('Exploring online retail for lab coats and scrubs across Egypt and Sudan.','استكشاف البيع الإلكتروني للابكوت والملابس الطبية في مصر والسودان.'),pair('COMMERCE / REGIONAL MARKETS','تجارة / أسواق إقليمية')]
];
const faqs=[
[pair('Can we start with just an idea?','هل يمكن البدء بفكرة فقط؟'),pair('Yes. Start with the problem, who experiences it, and what you want to achieve. Discovery helps define a sensible first version before committing to a large scope.','نعم. نبدأ بالمشكلة ومن يواجهها وما تريد تحقيقه. يساعد الاستكشاف في تحديد نسخة أولى مناسبة قبل الالتزام بنطاق كبير.')],
[pair('Can you improve an existing product?','هل يمكن تحسين منتج قائم؟'),pair('Yes. We start by reviewing the architecture, user journeys, and current constraints. Then we agree on a focused improvement plan.','نعم. نبدأ بمراجعة البنية ورحلات المستخدم والقيود الحالية، ثم نتفق على خطة تحسين محددة.')],
[pair('How are timelines and budgets decided?','كيف تُحدد المدة والميزانية؟'),pair('They depend on scope, integrations, design readiness, and delivery requirements. We agree on milestones and responsibilities after reviewing the project.','تعتمد على النطاق والتكاملات وجاهزية التصميم ومتطلبات التسليم. نتفق على المراحل والمسؤوليات بعد مراجعة المشروع.')],
[pair('Who will build our product?','من سيبني منتجنا؟'),pair('We agree on project ownership, responsibilities, and communication before work begins. Yousif leads the studio as founder; specialist collaboration is scoped to the needs of each engagement.','نحدد ملكية المشروع والمسؤوليات والتواصل قبل بدء العمل. يقود يوسف الاستوديو بصفته المؤسس، ويُحدد التعاون مع المختصين وفق احتياجات كل مشروع.')]
];
let lang='en',filter='all',activeProject=null;
const $=id=>document.getElementById(id),t=v=>v[lang],esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readPref=k=>{try{return localStorage.getItem(k)}catch{return null}},writePref=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
function renderProjects(){
 const options=[['all',pair('All projects','كل المشاريع')],['systems',pair('Business platforms','منصات الأعمال')],['ai',pair('Applied AI','ذكاء اصطناعي تطبيقي')]];
 $('filters').innerHTML=options.map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${esc(t(label))}</button>`).join('');
 $('projects').innerHTML=projects.filter(p=>filter==='all'||p.category===filter).map(p=>caseStudy(p)).join('');
}
const L=(en,ar)=>lang==='en'?en:ar;
const mockupDescriptions={
 noor:[pair('Customer shopping, vendor orders and Noor administration on three phones','التسوق وطلبات التجار وإدارة نور على ثلاثة هواتف'),pair('Product browsing and product details on two overlapping phones','تصفح المنتجات وتفاصيلها على هاتفين متداخلين'),pair('NOOR product detail and add-to-cart interface','تفاصيل منتج نور وإضافته إلى السلة'),pair('Cart and cash-on-delivery checkout','السلة وإتمام الطلب بالدفع عند الاستلام'),pair('Vendor order confirmation and preparation','تأكيد طلبات التاجر وتجهيزها'),pair('Noor delivery operations and ready orders','عمليات توصيل نور والطلبات الجاهزة'),pair('Customer profile, addresses and order history','ملف العميل والعناوين وسجل الطلبات')],
 crop:[pair('Leaf capture, analysis and history on three phones','التقاط الورقة والتحليل والسجل على ثلاثة هواتف'),pair('Leaf capture and analysis on two overlapping phones','التقاط الورقة وتحليلها على هاتفين متداخلين'),pair('Leaf classification results and confidence context','نتائج تصنيف الورقة وسياق الثقة'),pair('Previous leaf analysis history','سجل تحليلات الأوراق السابقة'),pair('Guidance for capturing a useful leaf photo','إرشادات تصوير الورقة بصورة مفيدة'),pair('Connected Crop Care AI assistant','مساعد Crop Care المتصل بالإنترنت'),pair('Crop Care profile and settings','الملف والإعدادات في Crop Care')],
 marketplace:[pair('Customer discovery, provider jobs and administration on three phones','اكتشاف الخدمات وأعمال مقدم الخدمة والإدارة على ثلاثة هواتف'),pair('Service discovery and provider profile on two overlapping phones','اكتشاف الخدمات وملف مقدمها على هاتفين متداخلين'),pair('Provider profile, service coverage and request action','ملف مقدم الخدمة والتغطية وطلب الخدمة'),pair('Service request with photos, location and preferred time','طلب خدمة بالصور والموقع والوقت المناسب'),pair('Provider requests with accept and decline actions','طلبات مقدم الخدمة مع القبول والرفض'),pair('Job progress from acceptance to completion','تقدم العمل من القبول إلى الإكمال'),pair('Customer profile, jobs and completed-job reviews','ملف العميل والأعمال وتقييمات الأعمال المكتملة')]
};
const mockupSrc=(p,i)=>`assets/images/mockups/${p.id}-${i}.webp`;
function mockupImage(p,i,eager=false){return `<img src="${mockupSrc(p,i)}" width="1600" height="${i===0?1600:1200}" alt="${esc(t(p.title))} — ${esc(t(mockupDescriptions[p.id][i]))} · ${L('concept mockup','نموذج تصوري')}" loading="${eager?'eager':'lazy'}" decoding="async"${eager?' fetchpriority="high"':''}>`;}
function mockupFigure(p,i,hero=false){return `<figure class="mockup-frame ${hero?'mockup-hero':i===6?'mockup-final':''}" data-mockup="${i}">${mockupImage(p,i,hero)}</figure>`;}
const mockupGrid=(p,indices)=>`<div class="mockup-grid mockup-grid-${indices.length}">${indices.map(i=>mockupFigure(p,i)).join('')}</div>`;
const mockupDisclosure=()=>L('Presentation mockups · illustrative interfaces','نماذج عرض · واجهات توضيحية');
function caseStudy(p){
 const content={
  noor:{category:pair('Commerce ecosystem','منظومة تجارة'),hook:pair('One marketplace. Every part connected.','سوق واحد. وكل جزء مترابط.'),tags:[pair('Customer app','تطبيق العملاء'),pair('Vendor workspace','مساحة التجار'),pair('Operations','العمليات')]},
  crop:{category:pair('On-device AI','ذكاء على الجهاز'),hook:pair('A leaf image. A clearer next step.','صورة ورقة. خطوة قادمة أوضح.'),tags:[pair('Capture','التقاط'),pair('Local analysis','تحليل محلي'),pair('AI assistant','مساعد ذكي')]},
  marketplace:{category:pair('Service marketplace','سوق خدمات'),hook:pair('Local expertise. One clear journey.','خبرة محلية. رحلة واضحة.'),tags:[pair('Discovery','اكتشاف'),pair('Job requests','طلبات العمل'),pair('Progress','متابعة التقدم')]}
 }[p.id];
 return `<article id="case-${p.id}" class="project-card visual-project ${p.id==='noor'?'visual-featured':''}"><a class="visual-project-image" href="#project/${p.id}" aria-label="${L('Explore','استكشف')} ${esc(t(p.title))}">${mockupImage(p,0)}<span class="visual-category">${esc(t(content.category))}</span></a><div class="visual-project-body"><div class="visual-project-title"><h3>${esc(t(p.title))}</h3><span class="project-stage">${esc(t(p.status))}</span></div><p>${esc(t(content.hook))}</p><div class="visual-project-bottom"><div class="project-capabilities">${content.tags.map(tag=>`<span>${esc(t(tag))}</span>`).join('')}</div><a href="#project/${p.id}" class="button primary">${L('View project','استعرض المشروع')}</a></div><small class="project-concept">${mockupDisclosure()}</small></div></article>`;
}
let carouselPaused=false;
function renderCarousel(){
 const sequence=projects.flatMap(p=>[0,1].map(i=>({p,i})));
 const group=duplicate=>`<div class="carousel-group"${duplicate?' aria-hidden="true"':''}>${sequence.map(({p,i})=>`<a class="carousel-slide" href="#project/${p.id}"${duplicate?' tabindex="-1"':''}><div>${mockupImage(p,i)}</div><span><b>${esc(t(p.title))}</b><small>${esc(t(p.status))}</small></span></a>`).join('')}</div>`;
 $('project-carousel-track').innerHTML=group(false)+group(true);
 updateCarouselLabel();
}
function updateCarouselLabel(){
 const off=motionPaused||reducedMotion.matches;
 $('carousel-toggle').disabled=off;
 $('carousel-toggle').textContent=off?L('Motion is off','الحركة متوقفة'):carouselPaused?L('Play carousel','تشغيل العرض'):L('Pause carousel','إيقاف العرض');
 $('carousel-toggle').setAttribute('aria-pressed',String(carouselPaused));
 $('project-carousel-track').dataset.paused=String(carouselPaused);
}
function renderAll(){
 document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
 document.querySelectorAll('[data-en][data-ar]').forEach(el=>el.textContent=el.dataset[lang]);
 $('language').textContent=lang==='en'?'عربي':'EN';$('language').lang=lang==='en'?'ar':'en';$('language').ariaLabel=lang==='en'?'Switch to Arabic':'التبديل إلى الإنجليزية';
 document.title=lang==='en'?'Yousif Digital | Product Design & Software Engineering':'يوسف ديجيتال | تصميم المنتجات وهندسة البرمجيات';
 $('filters').ariaLabel=lang==='en'?'Filter projects':'تصفية المشاريع';$('close-dialog').ariaLabel=lang==='en'?'Back to projects':'العودة للمشاريع';
 renderProjects();renderCarousel();
 $('service-list').innerHTML=services.map(([title,desc,tags],i)=>`<article class="service-card"><span class="service-number">0${i+1}</span><h3>${esc(t(title))}</h3><p>${esc(t(desc))}</p><div class="tags">${tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></article>`).join('');

 $('process-list').innerHTML=processes.map(([title,desc],i)=>`<article class="process-card"><span>0${i+1}</span><h3>${esc(t(title))}</h3><p>${esc(t(desc))}</p></article>`).join('');
 $('lab-list').innerHTML=labs.map(([title,status,desc,type])=>`<article class="lab-card"><span class="lab-status">${esc(t(status))}</span><h3>${esc(t(title))}</h3><p>${esc(t(desc))}</p><div class="lab-type">${esc(t(type))}</div></article>`).join('');
 $('faq-list').innerHTML=faqs.map(([q,a])=>`<details><summary>${esc(t(q))}</summary><p>${esc(t(a))}</p></details>`).join('');
 if(activeProject)renderDialog(activeProject);updateThemeLabel();refreshMotion();
}
const featureTopics={noor:[pair('Shopping & checkout','التسوق وإتمام الطلب'),pair('Vendor privacy','خصوصية التجار'),pair('Administration & localization','الإدارة واللغات'),pair('Vendor onboarding','انضمام التجار'),pair('Multi-vendor orders','طلبات متعددة التجار'),pair('Role permissions','صلاحيات الأدوار'),pair('Coupons & first orders','الكوبونات وأول طلب'),pair('Notifications & broadcasts','الإشعارات والتنبيهات العامة'),pair('Analytics & KPIs','التحليلات ومؤشرات الأداء'),pair('Arabic & English','العربية والإنجليزية'),pair('Release & readiness','الإصدار والاستعداد')],crop:[pair('Model integration','ربط النموذج'),pair('Capture & history','الالتقاط والسجل'),pair('State & assistant','الحالة والمساعد'),pair('Research evaluation','التقييم البحثي'),pair('Local vs connected features','الميزات المحلية والمتصلة')],marketplace:[pair('Product architecture','بنية المنتج'),pair('Requests & quotes','الطلبات وعروض السعر'),pair('Trust & oversight','الثقة والإشراف'),pair('Job lifecycle','دورة العمل'),pair('Operating rules','قواعد التشغيل')]};
const detailStories={
 noor:{hook:pair('A storefront is only the start.','واجهة المتجر هي البداية فقط.'),promise:pair('Connect the people who shop, sell, and keep orders moving.','اربط من يتسوق ويبيع ويدير حركة الطلبات.')},
 crop:{hook:pair('From AI research to a useful daily tool.','من بحث في الذكاء إلى أداة عملية.'),promise:pair('A leaf image. Local analysis. A clearer next step.','صورة ورقة. تحليل محلي. خطوة قادمة أوضح.')},
 marketplace:{hook:pair('Good service begins with trust.','الخدمة الجيدة تبدأ بالثقة.'),promise:pair('Bring customers, craftspeople, and operations into one clear workflow.','اجمع العملاء والحرفيين والعمليات في مسار واضح.')}
};
function renderDialog(p){
 const d=detailStories[p.id],crop=p.id==='crop',noor=p.id==='noor';
 $('project-dialog').dataset.project=p.id;
 document.title=`${t(p.title)} | Yousif Digital`;
 const visual=`${mockupFigure(p,0,true)}<p class="mockup-disclosure">${mockupDisclosure()}</p>`;
 const featureList=(from,to)=>`<ul>${p.features.slice(from,to).map((f,i)=>`<li><strong>${esc(t(featureTopics[p.id][from+i]))}.</strong> ${esc(t(f))}</li>`).join('')}</ul>`;
 const title2=noor?L('One order. A coordinated operation.','طلب واحد. عملية تشغيل مترابطة.'):crop?L('Intelligence that runs on the device.','ذكاء يعمل على الجهاز.'):L('Trust is part of the workflow.','الثقة جزء من مسار العمل.');
 const title3=noor?L('Visibility for the people behind the business.','رؤية واضحة للقائمين على الأعمال.'):crop?L('Research translated into a mobile experience.','بحث تحول إلى تجربة هاتف.'):L('A considered foundation before implementation.','أساس مدروس قبل التنفيذ.');
 const note=noor?L('NOOR is in active development. The MVP uses cash on delivery, with Noor managing delivery in-house. The first ordering rollout is scoped to Sinnar. Public launch and commercial results are not claimed.','نور قيد التطوير. تستخدم النسخة الأولى الدفع عند الاستلام، وتدير نور التوصيل داخليًا. يبدأ نطاق الطلبات بسنار. لا ندعي إطلاقًا عامًا أو نتائج تجارية.'):crop?L('Reported per-class F1 scores range from 0.90 to 0.97. These describe academic model evaluation; they do not promise accuracy under every field condition. Mobile development and model integration were contributed alongside the AI teammates.','تتراوح قيم F1 المبلغ عنها من 0.90 إلى 0.97، وهي تصف تقييمًا أكاديميًا للنموذج ولا تضمن الدقة في كل ظروف الحقل. ساهم تطوير الهاتف وربط النموذج إلى جانب أعضاء فريق الذكاء الاصطناعي.'):L('The marketplace is at discovery and proposal stage. Customer and provider journeys, approval rules, quotes, job history, reviews, and administrative oversight describe the proposed MVP.','المنصة في مرحلة الاستكشاف والمقترح. تصف رحلات العملاء ومقدمي الخدمة وقواعد الاعتماد والعروض والسجل والتقييمات والإشراف النسخة الأولية المقترحة.');
 $('dialog-content').innerHTML=`<article class="reference-overview"><div class="reference-intro"><h1 id="dialog-title" tabindex="-1">${esc(t(p.title))}</h1><p>${esc(t(p.desc))}</p><a class="button secondary" href="#contact">${L('Discuss a similar project','ناقش مشروعًا مشابهًا')}</a></div>${visual}<dl class="reference-metadata"><div><dt>${L('CLIENT / PROJECT','العميل / المشروع')}</dt><dd>${esc(t(p.title))}</dd></div><div><dt>${L('SERVICE PROVIDED','الخدمات المقدمة')}</dt><dd>${noor?L('Product architecture, mobile development, backend & administration','بنية المنتج وتطوير الهاتف والخلفية والإدارة'):crop?L('Mobile development & on-device AI integration','تطوير الهاتف وربط الذكاء الاصطناعي على الجهاز'):L('Product discovery, user journeys & system design','استكشاف المنتج ورحلات المستخدم وتصميم النظام')}</dd></div><div><dt>${L('PROJECT STAGE','مرحلة المشروع')}</dt><dd>${esc(t(p.status))}</dd></div></dl></article><div class="reference-narrative"><section class="reference-copy"><h2>${esc(t(d.hook))}</h2><p>${esc(t(p.problem))}</p><p>${esc(t(p.role))}</p></section>${mockupGrid(p,[1,2])}<section class="reference-copy"><h2>${title2}</h2><p>${esc(t(d.promise))}</p>${featureList(0,noor?6:3)}</section>${mockupGrid(p,[3,4,5])}<section class="reference-copy"><h2>${title3}</h2>${featureList(noor?6:3,p.features.length)}<p>${note}</p><div class="reference-tech" dir="ltr">${esc(p.stack)}</div>${p.url?`<a class="text-button" href="${p.url}" target="_blank" rel="noopener noreferrer">${L('Explore the repository','استكشف المستودع')}</a>`:''}</section>${mockupFigure(p,6)}</div><section class="reference-related"><h2>${L('More projects','مشاريع أخرى')}</h2><div>${projects.filter(x=>x.id!==p.id).map(x=>`<a href="#project/${x.id}" class="reference-related-card"><div>${mockupImage(x,0)}</div><h3>${esc(t(x.title))}</h3><p>${esc(t(x.type))}</p></a>`).join('')}</div></section><section class="reference-cta"><span class="eyebrow">${L('Start a conversation','ابدأ محادثة')}</span><h2>${L('Ready to build your next product?','جاهز لبناء منتجك القادم؟')}</h2><p>${L('Tell us the business challenge. We’ll map the product, priorities, and a practical path forward.','أخبرنا بتحدي أعمالك. نحدد معك المنتج والأولويات والمسار العملي للتنفيذ.')}</p><a href="#contact" class="button primary">${L('Discuss your project','ناقش مشروعك')}</a></section><footer class="reference-footer"><b>yousif digital.</b><p>${L('Product strategy. Design. Software engineering.','استراتيجية المنتجات. التصميم. هندسة البرمجيات.')}</p><a href="#work">${L('Back to projects','العودة للمشاريع')}</a></footer>`;
}
function syncProjectRoute(){
 const match=window.location.hash.match(/^#project\/(noor|crop|marketplace)$/);
 activeProject=match?projects.find(p=>p.id===match[1]):null;
 document.documentElement.dataset.view=activeProject?'project':'home';
 $('project-dialog').hidden=!activeProject;
 if(activeProject){renderDialog(activeProject);window.scrollTo({top:0,behavior:'instant'});$('dialog-title').focus({preventScroll:true});}
 else{document.title=lang==='en'?'Yousif Digital | Product Design & Software Engineering':'يوسف ديجيتال | تصميم المنتجات وهندسة البرمجيات';if(window.location.hash){const target=document.getElementById(window.location.hash.slice(1));if(target)target.scrollIntoView({behavior:'instant'});}}
}
window.addEventListener('hashchange',syncProjectRoute);

$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;renderProjects();$('filters').querySelector(`[data-filter="${filter}"]`).focus();refreshMotion()});
$('projects').addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)window.location.hash=`project/${b.dataset.project}`;});
$('carousel-toggle').addEventListener('click',()=>{carouselPaused=!carouselPaused;updateCarouselLabel()});
$('close-dialog').addEventListener('click',()=>{window.location.hash='work'});
$('language').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';writePref('portfolio-language',lang);$('copy-status').textContent='';renderAll()});
function updateThemeLabel(){const dark=document.documentElement.dataset.theme==='dark';$('theme').ariaLabel=lang==='en'?(dark?'Switch to light theme':'Switch to dark theme'):(dark?'تفعيل المظهر الفاتح':'تفعيل المظهر الداكن')}
$('theme').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';writePref('portfolio-theme',document.documentElement.dataset.theme);updateThemeLabel()});
$('menu').addEventListener('click',()=>{const expanded=$('menu').getAttribute('aria-expanded')==='true';$('menu').setAttribute('aria-expanded',String(!expanded));$('nav-links').classList.toggle('open',!expanded)});
$('nav-links').addEventListener('click',e=>{if(e.target.closest('a')){$('menu').setAttribute('aria-expanded','false');$('nav-links').classList.remove('open')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('menu').setAttribute('aria-expanded','false');$('nav-links').classList.remove('open')}});
$('copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('yousifkhalid544@gmail.com');$('copy-status').textContent=lang==='en'?'Email copied.':'تم نسخ البريد.'}catch{$('copy-status').textContent=lang==='en'?'Select the email above to copy it.':'حدد البريد أعلاه لنسخه.'}});
$('contact-form').addEventListener('submit',e=>{e.preventDefault();const name=$('name').value.trim(),email=$('email').value.trim(),message=$('message').value.trim();if(!name||!message)return;const subject=lang==='en'?`Project enquiry from ${name}`:`استفسار مشروع من ${name}`;const body=`${name}\n${email}\n\n${message}`;window.location.href=`mailto:yousifkhalid544@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});

let revealObserver=null;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
let motionPaused=readPref('studio-motion')==='off';
function refreshMotion(){
 const off=motionPaused||reducedMotion.matches;
 document.documentElement.dataset.motion=off?'off':'on';
 $('motion-toggle').textContent=lang==='en'?(off?'Enable motion':'Pause motion'):(off?'تفعيل الحركة':'إيقاف الحركة');
 $('motion-toggle').setAttribute('aria-pressed',String(off));updateCarouselLabel();
 if(revealObserver)revealObserver.disconnect();
 if(off||!('IntersectionObserver' in window)){document.documentElement.classList.remove('motion-ready');return;}
 document.documentElement.classList.add('motion-ready');
 revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}})},{threshold:.08,rootMargin:'0px 0px -25px 0px'});
 document.querySelectorAll('.heading,.impact-card,.service-card,.project-card,.process-card,.model-card,.company-grid,.lab-card,.faq>div,.contact-grid').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--reveal-delay',`${(i%3)*50}ms`);revealObserver.observe(el)});
}
$('motion-toggle').addEventListener('click',()=>{motionPaused=!motionPaused;writePref('studio-motion',motionPaused?'off':'on');refreshMotion()});
reducedMotion.addEventListener('change',refreshMotion);
lang=readPref('portfolio-language')==='ar'?'ar':'en';document.documentElement.dataset.theme=readPref('portfolio-theme')==='dark'?'dark':'light';renderAll();syncProjectRoute();
